import { Appointment } from "@/features/appointments/type/appointment";
import { Call } from "@/features/common/type/call";
import { Lead } from "@/features/leads/type/lead";

export const APPOINTMENTS: Appointment[] = [
    {
        id: "1",
        title: "Client Meeting",
        date: new Date("2026-05-01T09:00:00"),
        status: "A",
        description: "Discuss project",
    },
    {
        id: "2",
        title: "Sprint Planning",
        date: new Date("2026-05-01T11:30:00"),
        status: "B",
        description: "Plan tasks",
    },
    {
        id: "3",
        title: "Marketing Review",
        date: new Date("2026-05-02T10:15:00"),
        status: "C",
        description: "Review current",
    },
    {
        id: "4",
        title: "UI Feedback",
        date: new Date("2026-05-02T14:00:00"),
        status: "D",
        description: "Collect feedback",
    },
    {
        id: "5",
        title: "Investor Call",
        date: new Date("2026-05-03T08:45:00"),
        status: "A",
        description: "Present growth",
    },
    {
        id: "6",
        title: "Team Sync",
        date: new Date("2026-05-03T16:00:00"),
        status: "B",
        description: "Weekly sync",
    },
    {
        id: "7",
        title: "Customer Support",
        date: new Date("2026-05-04T09:20:00"),
        status: "C",
        description: "Handle escalated",
    },
    {
        id: "8",
        title: "Backend Review",
        date: new Date("2026-05-04T13:10:00"),
        status: "D",
        description: "Review API",
    },
    {
        id: "9",
        title: "Enterprise Demo",
        date: new Date("2026-05-05T10:00:00"),
        status: "A",
        description: "Live demo for enterprise clients.",
    },
    {
        id: "10",
        title: "Design Handoff",
        date: new Date("2026-05-05T15:30:00"),
        status: "B",
        description: "Transfer finalized designs to developers.",
    },
    {
        id: "11",
        title: "Optimization Review",
        date: new Date("2026-05-06T09:45:00"),
        status: "C",
        description: "Analyze performance bottlenecks in the app.",
    },
    {
        id: "12",
        title: "QA Session",
        date: new Date("2026-05-06T12:00:00"),
        status: "D",
        description: "Run quality assurance test cases.",
    },
    {
        id: "13",
        title: "Partnership Meeting",
        date: new Date("2026-05-07T11:15:00"),
        status: "A",
        description: "Discuss collaboration opportunities.",
    },
    {
        id: "14",
        title: "Roadmap Planning",
        date: new Date("2026-05-07T17:00:00"),
        status: "B",
        description: "Define product roadmap for Q3.",
    },
    {
        id: "15",
        title: "API Discussion",
        date: new Date("2026-05-08T08:30:00"),
        status: "C",
        description: "Review third-party API integrations.",
    },
    {
        id: "16",
        title: "Security Audit",
        date: new Date("2026-05-08T14:20:00"),
        status: "D",
        description: "Audit authentication and permissions flow.",
    },
    {
        id: "17",
        title: "Technical Interview",
        date: new Date("2026-05-09T09:10:00"),
        status: "A",
        description: "Interview frontend developer candidate.",
    },
    {
        id: "18",
        title: "Collaboration Call",
        date: new Date("2026-05-09T13:45:00"),
        status: "B",
        description: "Coordinate with cross-functional teams.",
    },
    {
        id: "19",
        title: "Dashboard Review",
        date: new Date("2026-05-10T10:40:00"),
        status: "C",
        description: "Review analytics dashboard metrics.",
    },
    {
        id: "20",
        title: "Support Escalation",
        date: new Date("2026-05-10T16:15:00"),
        status: "D",
        description: "Resolve urgent production issues.",
    },
    {
        id: "21",
        title: "Launch Prep",
        date: new Date("2026-05-11T09:35:00"),
        status: "A",
        description: "Prepare assets and checklist for launch.",
    },
    {
        id: "22",
        title: "Bug Triage",
        date: new Date("2026-05-11T15:00:00"),
        status: "B",
        description: "Prioritize newly reported bugs.",
    },
    {
        id: "23",
        title: "Vendor Meeting",
        date: new Date("2026-05-12T08:50:00"),
        status: "C",
        description: "Discuss infrastructure and hosting costs.",
    },
    {
        id: "24",
        title: "Deployment Check",
        date: new Date("2026-05-12T13:25:00"),
        status: "D",
        description: "Verify deployment readiness and rollback plan.",
    },
    {
        id: "25",
        title: "Brainstorm Session",
        date: new Date("2026-05-13T10:55:00"),
        status: "A",
        description: "Generate ideas for new app features.",
    },
    {
        id: "26",
        title: "Mobile Testing",
        date: new Date("2026-05-13T14:40:00"),
        status: "B",
        description: "Test app on multiple Android devices.",
    },
    {
        id: "27",
        title: "Onboarding Walkthrough",
        date: new Date("2026-05-14T09:25:00"),
        status: "C",
        description: "Guide new clients through onboarding.",
    },
    {
        id: "28",
        title: "Migration Planning",
        date: new Date("2026-05-14T16:30:00"),
        status: "D",
        description: "Plan database migration steps.",
    },
    {
        id: "29",
        title: "Strategy Meeting",
        date: new Date("2026-05-15T11:05:00"),
        status: "A",
        description: "Discuss long-term business strategy.",
    },
    {
        id: "30",
        title: "Release Coordination",
        date: new Date("2026-05-15T17:20:00"),
        status: "B",
        description: "Coordinate final production release tasks.",
    },
];

export const LEADS: Lead[] = [
    {
        id: "1",
        title: "Acme Corporation",
        type: "sales",
        last_contacted_at: "2026-05-01T10:30:00",
        priority: "high",
        status: "new",
    },
    {
        id: "2",
        title: "Bright Future Ltd",
        type: "pricing",
        last_contacted_at: "2026-05-01T14:00:00",
        priority: "medium",
        status: "connected",
    },
    {
        id: "3",
        title: "Nova Consulting",
        type: "consultation",
        last_contacted_at: "2026-05-02T09:15:00",
        priority: "low",
        status: "booked",
    },
    {
        id: "4",
        title: "Pixel Agency",
        type: "other",
        last_contacted_at: "2026-05-02T11:45:00",
        priority: "medium",
        status: "closed",
    },
    {
        id: "5",
        title: "Vertex Solutions",
        type: "tex_prepration",
        last_contacted_at: "2026-05-03T08:20:00",
        priority: "high",
        status: "connected",
    },
    {
        id: "6",
        title: "Skyline Media",
        type: "sales",
        last_contacted_at: "2026-05-03T16:10:00",
        priority: "low",
        status: "new",
    },
    {
        id: "7",
        title: "Quantum Tech",
        type: "pricing",
        last_contacted_at: "2026-05-04T12:30:00",
        priority: "high",
        status: "booked",
    },
    {
        id: "8",
        title: "Orbit Digital",
        type: "consultation",
        last_contacted_at: "2026-05-04T15:40:00",
        priority: "medium",
        status: "connected",
    },
    {
        id: "9",
        title: "BluePeak Systems",
        type: "sales",
        last_contacted_at: "2026-05-05T09:50:00",
        priority: "high",
        status: "closed",
    },
    {
        id: "10",
        title: "CloudNest",
        type: "other",
        last_contacted_at: "2026-05-05T13:25:00",
        priority: "low",
        status: "new",
    },
    {
        id: "11",
        title: "Evergreen Studio",
        type: "consultation",
        last_contacted_at: "2026-05-06T10:00:00",
        priority: "medium",
        status: "connected",
    },
    {
        id: "12",
        title: "Fusion Works",
        type: "pricing",
        last_contacted_at: "2026-05-06T17:20:00",
        priority: "high",
        status: "booked",
    },
    {
        id: "13",
        title: "Alpha Ventures",
        type: "sales",
        last_contacted_at: "2026-05-07T08:45:00",
        priority: "medium",
        status: "new",
    },
    {
        id: "14",
        title: "NextGen Labs",
        type: "tex_prepration",
        last_contacted_at: "2026-05-07T11:10:00",
        priority: "high",
        status: "connected",
    },
    {
        id: "15",
        title: "Zenith Group",
        type: "other",
        last_contacted_at: "2026-05-08T14:35:00",
        priority: "low",
        status: "closed",
    },
    {
        id: "16",
        title: "Silverline Corp",
        type: "pricing",
        last_contacted_at: "2026-05-08T18:00:00",
        priority: "medium",
        status: "booked",
    },
    {
        id: "17",
        title: "Inspire Media",
        type: "consultation",
        last_contacted_at: "2026-05-09T09:40:00",
        priority: "high",
        status: "new",
    },
    {
        id: "18",
        title: "PeakPoint",
        type: "sales",
        last_contacted_at: "2026-05-09T12:50:00",
        priority: "medium",
        status: "connected",
    },
    {
        id: "19",
        title: "Hexa Innovations",
        type: "other",
        last_contacted_at: "2026-05-10T10:25:00",
        priority: "low",
        status: "booked",
    },
    {
        id: "20",
        title: "PrimeCore",
        type: "tex_prepration",
        last_contacted_at: "2026-05-10T15:45:00",
        priority: "high",
        status: "closed",
    },
    {
        id: "21",
        title: "UrbanScale",
        type: "pricing",
        last_contacted_at: "2026-05-11T08:15:00",
        priority: "medium",
        status: "new",
    },
    {
        id: "22",
        title: "CoreBridge",
        type: "consultation",
        last_contacted_at: "2026-05-11T13:55:00",
        priority: "high",
        status: "connected",
    },
    {
        id: "23",
        title: "LaunchCraft",
        type: "sales",
        last_contacted_at: "2026-05-12T11:05:00",
        priority: "low",
        status: "booked",
    },
    {
        id: "24",
        title: "NorthWind",
        type: "other",
        last_contacted_at: "2026-05-12T16:30:00",
        priority: "medium",
        status: "closed",
    },
    {
        id: "25",
        title: "Spark Dynamics",
        type: "pricing",
        last_contacted_at: "2026-05-13T09:35:00",
        priority: "high",
        status: "new",
    },
    {
        id: "26",
        title: "Visionary Labs",
        type: "consultation",
        last_contacted_at: "2026-05-13T14:10:00",
        priority: "medium",
        status: "connected",
    },
    {
        id: "27",
        title: "Elevate Systems",
        type: "tex_prepration",
        last_contacted_at: "2026-05-14T10:20:00",
        priority: "high",
        status: "booked",
    },
    {
        id: "28",
        title: "BrightPath",
        type: "sales",
        last_contacted_at: "2026-05-14T17:15:00",
        priority: "low",
        status: "closed",
    },
    {
        id: "29",
        title: "Nimbus Tech",
        type: "other",
        last_contacted_at: "2026-05-15T12:00:00",
        priority: "medium",
        status: "new",
    },
    {
        id: "30",
        title: "Delta Partners",
        type: "pricing",
        last_contacted_at: "2026-05-15T18:40:00",
        priority: "high",
        status: "connected",
    },
];

export const CALLS: Call[] = [
    {
        id: "1",
        client_status: "A",
        phone: "+1 202-555-0101",
        time: new Date("2026-05-01T09:00:00"),
        status: "booked",
        reason: "tex-preparation",
    },
    {
        id: "2",
        client_status: "B",
        phone: "+1 202-555-0102",
        time: new Date("2026-05-01T10:30:00"),
        status: "completed",
        reason: "business-consulting",
    },
    {
        id: "3",
        client_status: "C",
        phone: "+1 202-555-0103",
        time: new Date("2026-05-01T12:15:00"),
        status: "follow-up",
        reason: "payrol-service",
    },
    {
        id: "4",
        client_status: "D",
        phone: "+1 202-555-0104",
        time: new Date("2026-05-01T14:00:00"),
        status: "booked",
        reason: "other",
    },
    {
        id: "5",
        client_status: "A",
        phone: "+1 202-555-0105",
        time: new Date("2026-05-02T09:45:00"),
        status: "completed",
        reason: "tex-preparation",
    },
    {
        id: "6",
        client_status: "B",
        phone: "+1 202-555-0106",
        time: new Date("2026-05-02T11:20:00"),
        status: "follow-up",
        reason: "business-consulting",
    },
    {
        id: "7",
        client_status: "C",
        phone: "+1 202-555-0107",
        time: new Date("2026-05-02T13:10:00"),
        status: "booked",
        reason: "payrol-service",
    },
    {
        id: "8",
        client_status: "D",
        phone: "+1 202-555-0108",
        time: new Date("2026-05-02T16:00:00"),
        status: "completed",
        reason: "other",
    },
    {
        id: "9",
        client_status: "A",
        phone: "+1 202-555-0109",
        time: new Date("2026-05-03T08:30:00"),
        status: "follow-up",
        reason: "tex-preparation",
    },
    {
        id: "10",
        client_status: "B",
        phone: "+1 202-555-0110",
        time: new Date("2026-05-03T10:45:00"),
        status: "booked",
        reason: "business-consulting",
    },
];
