import { Appointment } from "@/features/appointments/type/appointment";

export const APPOINTMENTS: Appointment[] = [
    {
        id: "1",
        title: "Client Meeting",
        date: new Date("2026-05-01T09:00:00"),
        status: "A",
        description: "Discuss project",
    },
    {
        id: "2",
        title: "Sprint Planning",
        date: new Date("2026-05-01T11:30:00"),
        status: "B",
        description: "Plan tasks",
    },
    {
        id: "3",
        title: "Marketing Review",
        date: new Date("2026-05-02T10:15:00"),
        status: "C",
        description: "Review current",
    },
    {
        id: "4",
        title: "UI Feedback",
        date: new Date("2026-05-02T14:00:00"),
        status: "D",
        description: "Collect feedback",
    },
    {
        id: "5",
        title: "Investor Call",
        date: new Date("2026-05-03T08:45:00"),
        status: "A",
        description: "Present growth",
    },
    {
        id: "6",
        title: "Team Sync",
        date: new Date("2026-05-03T16:00:00"),
        status: "B",
        description: "Weekly sync",
    },
    {
        id: "7",
        title: "Customer Support",
        date: new Date("2026-05-04T09:20:00"),
        status: "C",
        description: "Handle escalated",
    },
    {
        id: "8",
        title: "Backend Review",
        date: new Date("2026-05-04T13:10:00"),
        status: "D",
        description: "Review API",
    },
    {
        id: "9",
        title: "Enterprise Demo",
        date: new Date("2026-05-05T10:00:00"),
        status: "A",
        description: "Live demo for enterprise clients.",
    },
    {
        id: "10",
        title: "Design Handoff",
        date: new Date("2026-05-05T15:30:00"),
        status: "B",
        description: "Transfer finalized designs to developers.",
    },
    {
        id: "11",
        title: "Optimization Review",
        date: new Date("2026-05-06T09:45:00"),
        status: "C",
        description: "Analyze performance bottlenecks in the app.",
    },
    {
        id: "12",
        title: "QA Session",
        date: new Date("2026-05-06T12:00:00"),
        status: "D",
        description: "Run quality assurance test cases.",
    },
    {
        id: "13",
        title: "Partnership Meeting",
        date: new Date("2026-05-07T11:15:00"),
        status: "A",
        description: "Discuss collaboration opportunities.",
    },
    {
        id: "14",
        title: "Roadmap Planning",
        date: new Date("2026-05-07T17:00:00"),
        status: "B",
        description: "Define product roadmap for Q3.",
    },
    {
        id: "15",
        title: "API Discussion",
        date: new Date("2026-05-08T08:30:00"),
        status: "C",
        description: "Review third-party API integrations.",
    },
    {
        id: "16",
        title: "Security Audit",
        date: new Date("2026-05-08T14:20:00"),
        status: "D",
        description: "Audit authentication and permissions flow.",
    },
    {
        id: "17",
        title: "Technical Interview",
        date: new Date("2026-05-09T09:10:00"),
        status: "A",
        description: "Interview frontend developer candidate.",
    },
    {
        id: "18",
        title: "Collaboration Call",
        date: new Date("2026-05-09T13:45:00"),
        status: "B",
        description: "Coordinate with cross-functional teams.",
    },
    {
        id: "19",
        title: "Dashboard Review",
        date: new Date("2026-05-10T10:40:00"),
        status: "C",
        description: "Review analytics dashboard metrics.",
    },
    {
        id: "20",
        title: "Support Escalation",
        date: new Date("2026-05-10T16:15:00"),
        status: "D",
        description: "Resolve urgent production issues.",
    },
    {
        id: "21",
        title: "Launch Prep",
        date: new Date("2026-05-11T09:35:00"),
        status: "A",
        description: "Prepare assets and checklist for launch.",
    },
    {
        id: "22",
        title: "Bug Triage",
        date: new Date("2026-05-11T15:00:00"),
        status: "B",
        description: "Prioritize newly reported bugs.",
    },
    {
        id: "23",
        title: "Vendor Meeting",
        date: new Date("2026-05-12T08:50:00"),
        status: "C",
        description: "Discuss infrastructure and hosting costs.",
    },
    {
        id: "24",
        title: "Deployment Check",
        date: new Date("2026-05-12T13:25:00"),
        status: "D",
        description: "Verify deployment readiness and rollback plan.",
    },
    {
        id: "25",
        title: "Brainstorm Session",
        date: new Date("2026-05-13T10:55:00"),
        status: "A",
        description: "Generate ideas for new app features.",
    },
    {
        id: "26",
        title: "Mobile Testing",
        date: new Date("2026-05-13T14:40:00"),
        status: "B",
        description: "Test app on multiple Android devices.",
    },
    {
        id: "27",
        title: "Onboarding Walkthrough",
        date: new Date("2026-05-14T09:25:00"),
        status: "C",
        description: "Guide new clients through onboarding.",
    },
    {
        id: "28",
        title: "Migration Planning",
        date: new Date("2026-05-14T16:30:00"),
        status: "D",
        description: "Plan database migration steps.",
    },
    {
        id: "29",
        title: "Strategy Meeting",
        date: new Date("2026-05-15T11:05:00"),
        status: "A",
        description: "Discuss long-term business strategy.",
    },
    {
        id: "30",
        title: "Release Coordination",
        date: new Date("2026-05-15T17:20:00"),
        status: "B",
        description: "Coordinate final production release tasks.",
    },
];
